import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { mkdir } from 'node:fs/promises';
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: true });
const base = process.env.APP_URL || 'http://localhost:4183';
const errors = [];
await mkdir(new URL('../test-results/', import.meta.url), { recursive: true });
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
const page = await context.newPage();
page.on('pageerror', error => errors.push(error.message));
const leaves = () => page.getByRole('button', { name: /Worry leaves/ }).click();
const flowers = () => page.getByRole('button', { name: /Intention flowers/ }).click();
const savedGarden = () => page.evaluate(() => JSON.parse(localStorage.getItem('tell-the-tree.v1')));
try {
  await page.goto(base);
  await page.locator('#worry').waitFor();
  assert.equal(await page.locator('.opening').count(), 0);
  assert.ok(await page.locator('.tree-heart').isHidden());
  assert.equal(await page.locator('.chest, .chest-illumination, .diamond-count').count(), 0);
  assert.ok(await page.getByRole('button', { name: 'Take a breathing break' }).isVisible());
  assert.equal(await page.locator('.tree-heart-light, .tree-heart-click').count(), 0);
  assert.equal(await page.locator('.tap-hand').evaluate(el => getComputedStyle(el).animationName), 'hand-tap');

  // Legacy opening links and unknown hashes also land on the tree.
  for (const hash of ['opening', 'unknown']) {
    await page.goto(base + '/#' + hash);
    await page.locator('#worry').waitFor();
    assert.equal(await page.locator('body').getAttribute('data-view'), 'tree');
    assert.equal(await page.locator('.opening').count(), 0);
  }
  await page.goto(base);
  for (let i = 0; i < 6; i++) {
    await page.locator('#worry').fill(`Worry ${i}`);
    await page.getByRole('button', { name: 'Give it to the tree', exact: true }).click();
  }
  assert.ok(await page.locator('.leaf-flight').count() > 0);
  assert.equal(await page.locator('.tree-marker').count(), 0);
  assert.equal(await page.locator('.tree-heart').count(), 1);
  assert.ok(await page.locator('.tree-heart').isHidden());
  await page.getByRole('button', { name: 'Take a breathing break' }).click();
  await page.locator('.breathing-page').waitFor();
  await page.getByRole('button', { name: 'Return to the tree', exact: true }).click();
  await page.locator('#worry').waitFor();
  assert.ok(await page.locator('.tree-heart').isHidden());
  await page.getByRole('button', { name: 'Take a breathing break' }).click();
  await page.locator('.breathing-page').waitFor();
  await page.waitForFunction(() => JSON.parse(localStorage.getItem('tell-the-tree.v1')).breathingCompleted === true);
  await page.getByRole('button', { name: 'Return to the tree', exact: true }).click();
  await page.locator('#worry').waitFor();
  await page.reload();
  assert.ok(await page.locator('.tree-heart').isVisible());
  await page.screenshot({ path: 'test-results/tree-desktop.png', fullPage: true });
  await page.locator('.tree-heart').focus();
  await page.keyboard.press('Enter');
  await page.waitForURL('**/#garden');
  await page.locator('.collection-page').waitFor();
  assert.equal(await page.locator('.worry-card').count(), 6);
  await page.getByRole('button', { name: 'Reflect on worry: Worry 0', exact: true }).click();
  await page.getByRole('button', { name: /Not right now/ }).click();
  await page.getByRole('button', { name: 'Let it go', exact: true }).click();
  assert.equal(await page.getByRole('button', { name: /Worry leaves/ }).getAttribute('aria-pressed'), 'true');
  assert.equal(await page.locator('.worry-card').count(), 5);
  for (let i = 1; i < 6; i++) {
    await page.getByRole('button', { name: `Reflect on worry: Worry ${i}`, exact: true }).click();
    await page.getByRole('button', { name: /Yes, a small step/ }).click();
    await page.locator('#action-text').fill(`Small action ${i}`);
    await page.getByRole('button', { name: 'Let it bloom', exact: true }).click();
    assert.ok(await page.locator('.bloom-effect').count() > 0);
    assert.equal(await page.getByRole('button', { name: /Worry leaves/ }).getAttribute('aria-pressed'), 'true');
    assert.equal(await page.locator('.worry-card').count(), 5 - i);
    assert.equal((await savedGarden()).flowers.length, i);
  }
  await page.getByRole('link', { name: 'Back to your tree', exact: true }).click();
  assert.equal(await page.locator('.tree-marker, .tree-harvest-below, [data-do="harvest"]').count(), 0);
  await page.locator('.tree-heart').click();
  await flowers();
  assert.ok(await page.locator('#harvest-selected').isDisabled());
  await page.getByRole('button', { name: 'Select all', exact: true }).click();
  assert.equal(await page.getByRole('checkbox', { checked: true }).count(), 5);
  await page.getByRole('button', { name: 'Clear selection', exact: true }).click();
  assert.equal(await page.getByRole('checkbox', { checked: true }).count(), 0);
  await page.getByRole('checkbox', { name: 'Select intention: Small action 1', exact: true }).check();
  await page.getByRole('checkbox', { name: 'Select intention: Small action 3', exact: true }).check();
  await page.locator('#harvest-selected').click();
  assert.equal(await page.locator('.harvest-selection-preview li').count(), 2);
  await page.getByRole('button', { name: 'Keep choosing', exact: true }).click();
  assert.equal(await page.getByRole('checkbox', { checked: true }).count(), 2);
  assert.equal((await savedGarden()).flowers.length, 5);
  await page.evaluate(() => { window.originalSave = Storage.prototype.setItem; Storage.prototype.setItem = () => { throw new Error('Quota'); }; });
  await page.locator('#harvest-selected').click();
  await page.getByRole('button', { name: 'Create my diamond', exact: true }).click();
  assert.ok(await page.locator('#dialog').isVisible());
  assert.equal((await savedGarden()).flowers.length, 5);
  assert.match(await page.locator('#toast').textContent(), /could not save/);
  await page.evaluate(() => { Storage.prototype.setItem = window.originalSave; });
  await page.getByRole('button', { name: 'Create my diamond', exact: true }).click();
  assert.equal(await page.locator('.flower-card').count(), 3);
  let saved = await savedGarden();
  assert.deepEqual(saved.harvests[0].actions.map(a => a.action), ['Small action 1', 'Small action 3']);
  assert.deepEqual(saved.flowers.map(f => f.action), ['Small action 2', 'Small action 4', 'Small action 5']);
  assert.deepEqual(saved.harvests[0].actions.map(a => a.worry), ['Worry 1', 'Worry 3']);
  assert.ok(!JSON.stringify(saved).includes('Worry 0'));
  await page.getByRole('checkbox', { name: 'Select intention: Small action 2', exact: true }).check();
  await page.locator('#harvest-selected').click();
  await page.getByRole('button', { name: 'Create my diamond', exact: true }).click();
  await page.reload();
  await flowers();
  assert.equal(await page.locator('.flower-card').count(), 2);
  assert.equal(await page.getByRole('checkbox', { checked: true }).count(), 0);
  await page.getByRole('link', { name: 'Treasure', exact: true }).click();
  await page.locator('.treasure-page').waitFor();
  assert.equal(await page.locator('.harvest-card').count(), 2);
  await page.locator('.harvest-card').first().click();
  assert.equal(await page.locator('.action-history li').count(), 1);
  assert.match(await page.locator('.action-history').textContent(), /Small action 2/);
  assert.equal(await page.locator('.action-history .paired-worry').textContent(), 'Worry 2');
  await page.getByRole('button', { name: 'Delete this diamond', exact: true }).click();
  await page.getByRole('button', { name: 'Yes, delete this diamond', exact: true }).click();
  await page.reload();
  assert.equal(await page.locator('.harvest-card').count(), 1);
  await page.locator('.harvest-card').click();
  assert.equal(await page.locator('.action-history li').count(), 2);
  await page.keyboard.press('Escape');
  await page.getByRole('link', { name: 'Breathe', exact: true }).click();
  await page.waitForTimeout(4300);
  assert.equal(await page.locator('#phase-label').textContent(), 'Hold gently');
  await page.getByRole('button', { name: 'Pause breathing', exact: true }).click();
  const number = await page.locator('#breath-number').textContent();
  await page.waitForTimeout(1200);
  assert.equal(await page.locator('#breath-number').textContent(), number);
  await page.getByRole('button', { name: 'Resume breathing', exact: true }).click();
  await page.getByRole('button', { name: 'Review your worries', exact: true }).click();
  await page.locator('.collection-page').waitFor();
  assert.equal(await page.getByRole('button', { name: /Worry leaves/ }).getAttribute('aria-pressed'), 'true');
  const mobile = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, reducedMotion: 'reduce' });
  const m = await mobile.newPage();
  m.on('pageerror', e => errors.push(e.message));
  await m.goto(base);
  await m.locator('#worry').waitFor();
  assert.ok(await m.locator('.tree-heart').isHidden());
  assert.equal(await m.locator('.opening').count(), 0);
  assert.equal(await m.locator('.tap-hand').evaluate(el => getComputedStyle(el).animationName), 'none');
  assert.equal(await m.locator('.chest, .chest-illumination').count(), 0);
  await m.locator('.tree-summary [data-do="leaves"]').tap();
  await m.getByRole('heading', { name: 'A little room to breathe.' }).waitFor();
  await m.getByRole('button', { name: /Intention flowers/ }).click();
  await m.getByRole('heading', { name: 'Every small step can bloom.' }).waitFor();
  await m.getByRole('link', { name: 'Back to your tree', exact: true }).click();
  await m.locator('#worry').fill('<img src=x onerror=alert(1)>');
  await m.getByRole('button', { name: 'Give it to the tree', exact: true }).click();
  assert.equal(await m.locator('.leaf-flight').count(), 0);
  assert.ok(await m.locator('.tree-heart').isHidden());
  await m.locator('.tree-summary [data-do="leaves"]').tap();
  assert.equal(await m.locator('.collection-text img').count(), 0);
  await m.locator('.worry-card').tap();
  assert.equal(await m.locator('blockquote img').count(), 0);
  await m.getByRole('button', { name: /Yes, a small step/ }).click();
  await m.locator('#action-text').fill('One mobile intention');
  await m.getByRole('button', { name: 'Let it bloom', exact: true }).click();
  assert.equal(await m.getByRole('button', { name: /Worry leaves/ }).getAttribute('aria-pressed'), 'true');
  await m.getByRole('heading', { name: 'A little room to breathe.' }).waitFor();
  await m.getByRole('button', { name: /Intention flowers/ }).click();
  await m.getByRole('checkbox').check();
  await m.locator('#harvest-selected').tap();
  await m.getByRole('button', { name: 'Create my diamond', exact: true }).tap();
  await m.getByRole('heading', { name: 'Every small step can bloom.' }).waitFor();
  assert.equal(await m.evaluate(() => JSON.parse(localStorage.getItem('tell-the-tree.v1')).harvests[0].actions.length), 1);
  assert.ok(await m.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await m.getByRole('link', { name: 'Back to your tree', exact: true }).click();
  await m.locator('.chest').waitFor();
  assert.ok(await m.locator('.tree-heart').isHidden());
  assert.equal(await m.locator('.diamond-count').textContent(), '1');
  assert.equal(await m.locator('.chest').evaluate(el => getComputedStyle(el).mixBlendMode), 'normal');
  assert.equal(await m.locator('.chest-illumination i').first().evaluate(el => getComputedStyle(el).animationName), 'none');
  await m.reload();
  assert.equal(await m.locator('.diamond-count').textContent(), '1');
  await m.evaluate(() => { Storage.prototype.setItem = () => { throw new Error('Quota'); }; });
  await m.locator('#worry').fill('Must not lose my draft');
  await m.getByRole('button', { name: 'Give it to the tree', exact: true }).click();
  assert.equal(await m.locator('#worry').inputValue(), 'Must not lose my draft');
  assert.match(await m.locator('#toast').textContent(), /could not save/);
  const corrupt = await browser.newContext(); const c = await corrupt.newPage();
  await c.goto(base + '/#tree');
  await c.evaluate(() => localStorage.setItem('tell-the-tree.v1', 'broken'));
  await c.reload();
  await c.locator('.storage-banner').waitFor();
  assert.equal(await c.evaluate(() => localStorage.getItem('tell-the-tree.v1')), 'broken');
  assert.deepEqual(errors, []);
  console.log('PASS: glow entrance, leaf reflection/release/actions, selected and single-flower harvests, cancellation, failed saves, persistence, treasure, breathing, mobile, reduced motion and escaped input.');
} finally { await browser.close(); }
