import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { mkdir } from 'node:fs/promises';
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: true });
const base = process.env.APP_URL || 'http://localhost:4183';
const errors = [];
await mkdir(new URL('../test-results/', import.meta.url), { recursive: true });
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
const page = await context.newPage();
page.on('pageerror', error => errors.push(error.message));
const savedGarden = () => page.evaluate(() => JSON.parse(localStorage.getItem('tell-the-tree.v1')));
try {
  await page.goto(base);
  await page.locator('#worry').waitFor();
  assert.equal(await page.locator('.opening').count(), 0);
  assert.ok(await page.locator('.tree-heart').isHidden());
  assert.equal(await page.locator('.chest, .chest-illumination, .diamond-count').count(), 0);
  assert.ok(await page.getByRole('button', { name: 'Take a breathing break' }).isVisible());
  assert.equal(await page.locator('.tree-heart-light, .tree-heart-click').count(), 0);
  assert.equal(await page.locator('.tap-hand').evaluate(el => getComputedStyle(el).animationName), 'hand-tap');

  // Legacy opening links and unknown hashes also land on the tree.
  for (const hash of ['opening', 'unknown']) {
    await page.goto(base + '/#' + hash);
    await page.locator('#worry').waitFor();
    assert.equal(await page.locator('body').getAttribute('data-view'), 'tree');
    assert.equal(await page.locator('.opening').count(), 0);
  }
  await page.goto(base);
  for (let i = 0; i < 6; i++) {
    await page.locator('#worry').fill(`Worry ${i}`);
    await page.getByRole('button', { name: 'Give it to the tree', exact: true }).click();
  }
  assert.ok(await page.locator('.leaf-flight').count() > 0);
  assert.equal(await page.locator('.tree-marker').count(), 0);
  assert.equal(await page.locator('.tree-heart').count(), 1);
  assert.ok(await page.locator('.tree-heart').isHidden());
  await page.getByRole('button', { name: 'Take a breathing break' }).click();
  await page.locator('.breathing-page').waitFor();
  await page.getByRole('button', { name: 'Return to the tree', exact: true }).click();
  await page.locator('#worry').waitFor();
  assert.ok(await page.locator('.tree-heart').isHidden());
  await page.getByRole('button', { name: 'Take a breathing break' }).click();
  await page.locator('.breathing-page').waitFor();
  await page.waitForFunction(() => JSON.parse(localStorage.getItem('tell-the-tree.v1')).breathingCompleted === true);
  await page.getByRole('button', { name: 'Return to the tree', exact: true }).click();
  await page.locator('#worry').waitFor();
  await page.reload();
  assert.ok(await page.locator('.tree-heart').isVisible());
  await page.screenshot({ path: 'test-results/tree-desktop.png', fullPage: true });
  await page.locator('.tree-heart').focus();
  await page.keyboard.press('Enter');
  await page.waitForURL('**/#garden');
  await page.locator('.collection-page').waitFor();
  assert.equal(await page.locator('.worry-node').count(), 6);
  await page.getByRole('button', { name: 'Reflect on worry: Worry 0', exact: true }).click();
  await page.getByRole('button', { name: /Not right now/ }).click();
  await page.getByRole('button', { name: 'Let it go', exact: true }).click();
  assert.ok(await page.locator('.bodhi-stage').isVisible());
  assert.equal(await page.locator('.worry-node').count(), 5);
  for (let i = 1; i < 6; i++) {
    const leaf = page.getByRole('button', { name: `Reflect on worry: Worry ${i}`, exact: true });
    const leafId = await leaf.getAttribute('data-leaf');
    const position = await leaf.getAttribute('style');
    await page.getByRole('button', { name: `Reflect on worry: Worry ${i}`, exact: true }).click();
    await page.getByRole('button', { name: /Yes, a small step/ }).click();
    await page.locator('#action-text').fill(`Small action ${i}`);
    await page.getByRole('button', { name: 'Let it bloom', exact: true }).click();
    assert.ok(await page.locator('.blooming').count() > 0);
    assert.equal(await page.locator(`[data-flower="${leafId}"]`).getAttribute('style'), position);
    assert.ok(await page.locator('.bodhi-stage').isVisible());
    assert.equal(await page.locator('.worry-node').count(), 5 - i);
    assert.equal((await savedGarden()).flowers.length, i);
  }
  await page.getByRole('link', { name: 'Back to your tree', exact: true }).click();
  assert.equal(await page.locator('.tree-marker, .tree-harvest-below, [data-do="harvest"]').count(), 0);
  await page.locator('.tree-heart').click();
  assert.equal(await page.getByRole('checkbox').count(), 0);
  await page.locator('.flower-node').first().click();
  assert.ok(await page.locator('.flower-detail .paired-worry').textContent());
  await page.keyboard.press('Escape');
  await page.evaluate(() => { window.originalSave = Storage.prototype.setItem; Storage.prototype.setItem = () => { throw new Error('Quota'); }; });
  await page.locator('#harvest-all').click();
  assert.equal((await savedGarden()).flowers.length, 5);
  assert.equal((await savedGarden()).harvests.length, 0);
  assert.match(await page.locator('#toast').textContent(), /could not save/);
  await page.evaluate(() => { Storage.prototype.setItem = window.originalSave; });
  await page.locator('#harvest-all').click();
  let saved = await savedGarden();
  assert.equal(saved.flowers.length, 0);
  assert.equal(saved.harvests.length, 1);
  assert.equal(saved.harvests[0].actions.length, 5);
  assert.deepEqual(saved.harvests[0].actions.map(a => a.worry), ['Worry 1','Worry 2','Worry 3','Worry 4','Worry 5']);
  assert.ok(await page.locator('#harvest-all').isDisabled());
  await page.reload();
  await page.getByRole('link', { name: 'Treasure', exact: true }).click();
  await page.locator('.harvest-card').click();
  assert.equal(await page.locator('.action-history li').count(), 5);
  await page.keyboard.press('Escape');
  await page.getByRole('link', { name: 'Breathe', exact: true }).click();
  await page.waitForTimeout(4300);
  assert.equal(await page.locator('#phase-label').textContent(), 'Hold gently');
  await page.getByRole('button', { name: 'Pause breathing', exact: true }).click();
  const number = await page.locator('#breath-number').textContent();
  await page.waitForTimeout(1200);
  assert.equal(await page.locator('#breath-number').textContent(), number);
  await page.getByRole('button', { name: 'Resume breathing', exact: true }).click();
  await page.getByRole('button', { name: 'Review your worries', exact: true }).click();
  await page.locator('.collection-page').waitFor();
  assert.ok(await page.locator('.bodhi-stage').isVisible());
  const mobile = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, reducedMotion: 'reduce' });
  const m = await mobile.newPage();
  m.on('pageerror', e => errors.push(e.message));
  await m.goto(base);
  await m.locator('#worry').waitFor();
  assert.ok(await m.locator('.tree-heart').isHidden());
  assert.equal(await m.locator('.opening').count(), 0);
  assert.equal(await m.locator('.tap-hand').evaluate(el => getComputedStyle(el).animationName), 'none');
  assert.equal(await m.locator('.chest, .chest-illumination').count(), 0);
  await m.locator('.tree-summary [data-do="leaves"]').tap();
  await m.getByRole('heading', { name: 'A little room to breathe.' }).waitFor();
  await m.getByRole('link', { name: 'Back to your tree', exact: true }).click();
  await m.locator('#worry').fill('<img src=x onerror=alert(1)>');
  await m.getByRole('button', { name: 'Give it to the tree', exact: true }).click();
  assert.equal(await m.locator('.leaf-flight').count(), 0);
  assert.ok(await m.locator('.tree-heart').isHidden());
  await m.locator('.tree-summary [data-do="leaves"]').tap();
  assert.equal(await m.locator('.collection-text img').count(), 0);
  await m.locator('.worry-node').tap();
  assert.equal(await m.locator('blockquote img').count(), 0);
  await m.getByRole('button', { name: /Yes, a small step/ }).click();
  await m.locator('#action-text').fill('One mobile intention');
  await m.getByRole('button', { name: 'Let it bloom', exact: true }).click();
  assert.equal(await m.locator('.flower-node').count(), 1);
  assert.equal(await m.locator('.blooming').count(), 0);
  await m.locator('#harvest-all').tap();
  await m.getByRole('heading', { name: 'A little room to breathe.' }).waitFor();
  assert.equal(await m.evaluate(() => JSON.parse(localStorage.getItem('tell-the-tree.v1')).harvests[0].actions.length), 1);
  assert.ok(await m.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await m.getByRole('link', { name: 'Back to your tree', exact: true }).click();
  await m.locator('.chest').waitFor();
  assert.ok(await m.locator('.tree-heart').isHidden());
  assert.equal(await m.locator('.diamond-count').textContent(), '1');
  assert.equal(await m.locator('.chest').evaluate(el => getComputedStyle(el).mixBlendMode), 'normal');
  assert.equal(await m.locator('.chest-illumination i').first().evaluate(el => getComputedStyle(el).animationName), 'none');
  await m.reload();
  assert.equal(await m.locator('.diamond-count').textContent(), '1');
  await m.evaluate(() => { Storage.prototype.setItem = () => { throw new Error('Quota'); }; });
  await m.locator('#worry').fill('Must not lose my draft');
  await m.getByRole('button', { name: 'Give it to the tree', exact: true }).click();
  assert.equal(await m.locator('#worry').inputValue(), 'Must not lose my draft');
  assert.match(await m.locator('#toast').textContent(), /could not save/);
  const corrupt = await browser.newContext(); const c = await corrupt.newPage();
  await c.goto(base + '/#tree');
  await c.evaluate(async () => {
    const m = await import('/model.js'); let g = m.blankGarden();
    for (let i = 0; i < 12; i++) {
      g = m.addWorry(g, 'Branch worry ' + i);
      if (i < 10) g = m.chooseAction(g, g.leaves.at(-1).id, 'Branch step ' + i);
    }
    localStorage.setItem(m.STORAGE_KEY, JSON.stringify(g));
  });
  await c.goto(base + '/#garden'); await c.reload();
  assert.equal(await c.locator('.bodhi-node').count(), 8);
  await c.locator('[data-do="next-branches"]').click();
  assert.equal(await c.locator('.bodhi-node').count(), 4);
  await c.locator('#harvest-all').click();
  const all = await c.evaluate(() => JSON.parse(localStorage.getItem('tell-the-tree.v1')));
  assert.equal(all.harvests[0].actions.length, 10);
  assert.equal(all.flowers.length, 0);
  assert.equal(all.leaves.length, 2);
  await c.evaluate(() => localStorage.setItem('tell-the-tree.v1', 'broken'));
  await c.reload();
  await c.locator('.storage-banner').waitFor();
  assert.equal(await c.evaluate(() => localStorage.getItem('tell-the-tree.v1')), 'broken');
  assert.deepEqual(errors, []);
  console.log('PASS: glow entrance, leaf reflection/release/actions, all-flower and single-flower harvests, failed saves, persistence, treasure, breathing, mobile, reduced motion and escaped input.');
} finally { await browser.close(); }
